version: '3.8'
services:
  fastmcp-server:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - ./config/.env
    volumes:
      - ./config:/app/config:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 5s
      retries: 3
